from typing import Annotated, Any, Dict, List
from typing_extensions import TypedDict
from langgraph.graph import MessagesState

from tradingagents.agents.utils.analyst_threads import merge_analyst_threads


def _merge_last_dict(existing: dict | None, new: dict | None) -> dict:
    """LangGraph reducer: keep the latest debate-state write in a parallel step."""
    if new is not None:
        return new
    return existing or {}


# Researcher team state
class InvestDebateState(TypedDict):
    bull_history: Annotated[
        str, "Bullish Conversation history"
    ]  # Bullish Conversation history
    bear_history: Annotated[
        str, "Bearish Conversation history"
    ]  # Bullish Conversation history
    history: Annotated[str, "Conversation history"]  # Conversation history
    summary: Annotated[str, "Compressed summary of earlier debate rounds"]
    current_response: Annotated[str, "Latest response"]  # Last response
    judge_decision: Annotated[str, "Final judge decision"]  # Last response
    count: Annotated[int, "Length of the current conversation"]  # Conversation length


# Risk management team state
class RiskDebateState(TypedDict):
    aggressive_history: Annotated[
        str, "Aggressive Agent's Conversation history"
    ]  # Conversation history
    conservative_history: Annotated[
        str, "Conservative Agent's Conversation history"
    ]  # Conversation history
    neutral_history: Annotated[
        str, "Neutral Agent's Conversation history"
    ]  # Conversation history
    history: Annotated[str, "Conversation history"]  # Conversation history
    summary: Annotated[str, "Compressed summary of earlier risk debate rounds"]
    latest_speaker: Annotated[str, "Analyst that spoke last"]
    current_aggressive_response: Annotated[
        str, "Latest response by the aggressive analyst"
    ]  # Last response
    current_conservative_response: Annotated[
        str, "Latest response by the conservative analyst"
    ]  # Last response
    current_neutral_response: Annotated[
        str, "Latest response by the neutral analyst"
    ]  # Last response
    judge_decision: Annotated[str, "Judge's decision"]
    count: Annotated[int, "Length of the current conversation"]  # Conversation length


class AgentState(MessagesState):
    # Isolated tool-call threads when analysts run in parallel (fan-out from START).
    analyst_threads: Annotated[Dict[str, List], merge_analyst_threads]

    company_of_interest: Annotated[str, "Company that we are interested in trading"]
    asset_type: Annotated[str, "Asset type under analysis such as stock or crypto"]
    trade_date: Annotated[str, "What date we are trading at"]

    sender: Annotated[str, "Agent that sent this message"]

    # research step
    market_report: Annotated[str, "Report from the Market Analyst"]
    sentiment_report: Annotated[str, "Report from the Sentiment Analyst"]
    news_report: Annotated[
        str, "Report from the News Researcher of current world affairs"
    ]
    fundamentals_report: Annotated[str, "Report from the Fundamentals Researcher"]
    verified_market_facts: Annotated[
        str,
        "Pre-fetched price/PE/PB (CN) injected before debate; agents must not invent valuation",
    ]
    tuige_setup: Annotated[
        str,
        "Tuige per-ticker setup module (trend-setups, relay-setups, etc.)",
    ]
    tuige_position_grade: Annotated[
        str,
        "Pre-computed Tuige position grade for PM sizing discipline",
    ]
    tuige_context_summary: Annotated[
        str,
        "Compact Tuige market context summary for reports",
    ]
    tuige_context: Annotated[
        Dict[str, Any],
        "Serialized TuigeContext for debate prompts (avoid duplicate fetches)",
    ]
    scheduled_event_alerts: Annotated[
        List[Dict[str, Any]],
        "Forward-looking scheduled corporate events (unlock, disclosure, ex-dividend)",
    ]
    report_quality_notes: Annotated[
        str,
        "Pre-debate quality gate notes for low-quality analyst reports",
    ]

    # researcher team discussion step
    investment_debate_state: Annotated[
        InvestDebateState,
        _merge_last_dict,
    ]
    investment_plan: Annotated[str, "Plan generated by the Analyst"]

    trader_investment_plan: Annotated[str, "Plan generated by the Trader"]

    # risk management team discussion step
    risk_debate_state: Annotated[
        RiskDebateState,
        _merge_last_dict,
    ]
    final_trade_decision: Annotated[str, "Final decision made by the Risk Analysts"]
    past_context: Annotated[str, "Memory log context injected at run start (same-ticker decisions + cross-ticker lessons)"]
